- hosts: all
  tasks:
  - name: print variables
    debug:
      msg: "Username: {{ diff_become_user }}"
  - name: Update all installed packages using APT module
    become: true
    become_user: "{{ diff_become_user }}"
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
    register: apt_update_status

  - name: Remove packages not needed anymore
    become: true
    become_user: "{{ diff_become_user }}"
    apt:
      autoremove: yes

  - name: Reboot when packages were updated
    become: true
    become_user: "{{ diff_become_user }}"
    reboot:
      post_reboot_delay: 60
    when: apt_update_status.changed