- hosts: "*"
  become: true
  become_user: root
  tasks:
    - name: Update (apt update)
      apt:
        update_cache: yes  
            
    - name: Upgrade (apt full-upgrade)
      apt:
        upgrade: full

    - name: Remove (apt autoremove)
      apt:
        autoremove: yes

    - name: Clean (apt autoclean)
      apt:
        autoclean: yes

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file    

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true