---

- hosts: all
  become: true
  become_user: $become_user
  tasks:
  - name: Update and upgrade apt packages
    apt:
      name: "*"
      state: latest
      update_cache: yes
      cache_valid_time: 86400 #One day
      force_apt_get: yes