- name: Prune unused Docker images
  hosts: all
  become: true
  become_user: root 
  tasks:
    - name: Prune images, containers, and build cache
      community.docker.docker_prune:
        containers: true
        images: true
        builder_cache: true