---

- hosts: all
  gather_facts: true
  become: true
  vars:
    server_url: "https://api.pushover.net/1/messages.json" # Replace with your server URL
    token: $(pushover_token) # token secret
    user: $(pushover_user) # user secret
    notification_title: "Updates"
    notification_message: "Updates have been applied and a reboot is necessary to complete the process on {{ ansible_hostname }} - {{ inventory_hostname }}"
  tasks:
    - ping:

    - name: Send notification
      ansible.builtin.uri:
        url: "{{ server_url }}"
        method: POST
        headers:
          token: "{{ token }}" # Replace 'api_token' with your token variable
          user: "{{ user }}"
          message: "{{ notification_title }}"
          Content-Type: "application/json" # Adjust as needed
        body_format: raw
        body: "{{ notification_message }}"
        status_code: 200 # Expect a 200 OK response

    - name: Display inventory hostname
      debug:
        msg: "{{ notification_message }}"