---

- hosts: all
  gather_facts: false
  become: true
  vars:
    ntfy_server_url: "https://notify.korkscrewgaming.com" # Replace with your ntfy server URL if self-hosting
    ntfy_token: $(ntfy_token) # ntfy token secret
    ntfy_topic: "general" # Replace with your desired ntfy topic
    notification_message: "Updates have been applied and a reboot is necessary to complete the process on {{ ansible_hostname }} - {{ inventory_hostname }}"
  tasks:
    - ping:
    - name: Send ntfy notification
      ansible.builtin.uri:
        url: "{{ ntfy_server_url }}/{{ ntfy_topic }}"
        method: POST
        headers:
          Authorization: "Bearer {{ ntfy_token }}" # Replace 'api_token' with your token variable
          Content-Type: "application/json" # Adjust as needed
        body_format: raw
        body: "{{ notification_message }}"
        status_code: 200 # Expect a 200 OK response
    - name: Display inventory hostname
      debug:
        msg: "{{ notification_message }}"